version: "2"
services:
    master_1:
        extends:
            file: common-services.yml
            service: common_master_1
    slave_1:
        extends:
            file: common-services.yml
            service: common_slave_1
        depends_on:
            - master_1
    master_2:
        extends:
            file: common-services.yml
            service: common_master_2
    slave_2:
        extends:
            file: common-services.yml
            service: common_slave_2
        depends_on:
            - master_2
    replication:
        extends:
            file: common-services.yml
            service: replication
        depends_on:
            - master_1
            - slave_1
            - master_2
            - slave_2
        command: bash ${REPL_SCRIPT_MOUNT_PATH}/slave-2-master-2-master-2-slave.sh
    pma:
        extends:
            file: common-services.yml
            service: pma
        depends_on:
            - master_1
            - slave_1
            - master_2
            - slave_2
            - replication
networks:
    replication_network:
        ipam:
            config:
                - subnet: 10.208.0.0/16
